# Generated by Django 5.1.4 on 2024-12-22 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acessorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Acessório')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='acessorios', verbose_name='Foto do acessório')),
            ],
        ),
        migrations.CreateModel(
            name='Cenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do cenário')),
                ('foto', models.ImageField(upload_to='cenarios', verbose_name='Foto do cenário')),
            ],
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do filme')),
                ('duracao', models.CharField(max_length=80, verbose_name='Duração')),
                ('ano', models.IntegerField(verbose_name='Ano de lançamento')),
                ('capa', models.ImageField(upload_to='capa_filmes', verbose_name='Capa do filme')),
                ('cenarios', models.ManyToManyField(related_name='filmes', to='api.cenario')),
            ],
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da música')),
                ('duracao', models.CharField(help_text='3m30', max_length=45, verbose_name='Duração da música')),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.filme', verbose_name='Filme')),
            ],
        ),
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do personagem')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='personagens', verbose_name='Foto do personagem')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('acessorio', models.ManyToManyField(blank=True, related_name='acessorios', to='api.acessorio')),
            ],
        ),
        migrations.AddField(
            model_name='filme',
            name='personagens',
            field=models.ManyToManyField(related_name='filmes', to='api.personagem'),
        ),
        migrations.CreateModel(
            name='Roupa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('foto', models.ImageField(upload_to='roupas', verbose_name='Foto da vestimenta')),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.personagem', verbose_name='Personagem')),
            ],
        ),
    ]
